---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

- name: update LB and db servers
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: creates directory
      file:
        path: /tmp/temp_dir
        state: directory

    - name: set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: run some shell script
      shell: echo "This is a test file..." > /tmp/temp_dir/temp_file