pipeline {
  agent any

  environment {
    ANSIBLE_CONFIG="/home/ubuntu/ansible-config-artifact/deploy/ansible.cfg"
  }

  parameters {
    string(name: 'inventory', defaultValue: 'dev', description: 'This is the inventory file for the environment to deploy configuration')
    string(name: 'tags', defaultValue: '', description: 'Specify the tag to limit the ansible execution')
  }

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }

      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }

      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
        }

      }
    }

    stage('Deploy') {
      options {
        timeout(time: 5, unit: 'MINUTES')
      }
      steps {
        script {
          sh 'echo "Deploy Stage"'
          ansiblePlaybook credentialsId: 'private_key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml', tags: '${tags}'
        }

      }
    }

    stage('Clean Up') {
      steps {
        script {
          sh 'echo "Clean Up Stage"'
        }

      }
    }

  }
}
